name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  build:
    # start up a container
    runs-on: ubuntu-latest
    steps:
      # take all codes in thie proj
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
