name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'

jobs:
  build:
    # start up a container
    runs-on: ubuntu-latest
    steps:
      # take all codes in thie proj
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
